spring:
    autoconfigure:
        exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
    main:
        allow-bean-definition-overriding: true
    shardingsphere:
        datasource:
            common:
                connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
                driver-class-name: com.alibaba.druid.pool.DruidDataSource
                filters: stat,wall,slf4j
                initial-size: 6
                max-active: 30
                max-wait: 60000
                maxPoolPreparedStatementPerConnectionSize: 20
                min-idle: 3
                minEvictableIdleTimeMillis: 300000
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                type: com.alibaba.druid.pool.DruidDataSource
                wall:
                    multi-statement-allow: true
            ds0_master:
                driver-class-name: com.mysql.jdbc.Driver
                password: root
                type: com.alibaba.druid.pool.DruidDataSource
                url: jdbc:mysql://192.168.10.251:3306/db_ds0_master?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
                username: root
            ds0_slave:
                driver-class-name: com.mysql.jdbc.Driver
                password: root
                type: com.alibaba.druid.pool.DruidDataSource
                url: jdbc:mysql://192.168.10.251:3306/db_ds0_slave?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
                username: root
            ds1_master:
                driver-class-name: com.mysql.jdbc.Driver
                password: root
                type: com.alibaba.druid.pool.DruidDataSource
                url: jdbc:mysql://192.168.10.251:3306/db_ds1_master?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
                username: root
            ds1_slave:
                driver-class-name: com.mysql.jdbc.Driver
                password: root
                type: com.alibaba.druid.pool.DruidDataSource
                url: jdbc:mysql://192.168.10.251:3306/db_ds1_slave?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
                username: root
            names: ds0_master,ds0_slave,ds1_master,ds1_slave
        props:
            sql-show: true
        rules:
            readwrite-splitting:
                data-sources:
                    ds-0:
                        load-balancer-name: alg_round
                        props:
                            read-data-source-names: ds0_slave
                            write-data-source-name: ds0_master
                        type: Static
                    ds-1:
                        load-balancer-name: alg_round
                        props:
                            read-data-source-names: ds1_slave
                            write-data-source-name: ds1_master
                        type: Static
                    readwrite_base:
                        load-balancer-name: alg_round
                        props:
                            read-data-source-names: ds10_base_slave
                            write-data-source-name: ds10_base_master
                        type: Static
                load-balancers:
                    alg_random:
                        type: RANDOM
                    alg_round:
                        type: ROUND_ROBIN
                    alg_weight:
                        props:
                            slave1: 10
                            slave2: 0
                        type: WEIGHT
            sharding:
                default-database-strategy:
                    standard:
                        sharding-algorithm-name: database-inline
                        sharding-column: user_id
                sharding-algorithms:
                    db-merchant-inline:
                        props:
                            algorithm-expression: ds-$->{merchant_id % 2}
                        type: INLINE
                    tb-merchant-inline:
                        props:
                            algorithm-expression: cms_merchant_$->{((int) (Integer.parseInt(Long.toString(merchant_id).substring(1))
                                / 2)) % 2}
                        type: INLINE
                tables:
                    cms_merchant:
                        actual-data-nodes: ds-$->{0..1}.cms_merchant_$->{0..1}
                        database-strategy:
                            standard:
                                sharding-algorithm-name: db-merchant-inline
                                sharding-column: merchant_id
                        table-strategy:
                            standard:
                                sharding-algorithm-name: tb-merchant-inline
                                sharding-column: merchant_id
        sharding:
            default-data-source-name: readwrite_base
