server:
    port: 8080
    address: localhost
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.10.251:3306/mybatisdemo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
        username: root
        password: root
        # 配置Druid连接池
        type: com.alibaba.druid.pool.DruidDataSource
        initial-size: 5  # 初始连接池大小
        min-idle: 5      # 最小空闲连接数
        max-active: 20    # 最大活跃连接数
        max-wait: 60000  # 获取连接的最大等待时间（毫秒）
        # Druid监控配置
        druid:
            stat-view-servlet:
                login-username: admin
                login-password: admin
                url-pattern: /druid/*
    application:
        name: MongoDB
    thymeleaf:
        # thymeleaf配置，开发环境不启用缓存，正式环境下请启用缓存，提高性能
        cache: false
        # thymeleaf对html元素格式要求严格，设置它的mode为HTML，忘记结束标签后不会报错
        mode: HTML
    http:
      encoding:
          # 编码
          charset: UTF-8
    servlet:
        multipart:
            # 文件上传限制
            max-file-size: 1024MB
            max-request-size: 1024MB
    # MongoDB 配置
    data:
        mongodb:
            uri: mongodb://admin:123456@192.168.10.251:27017/test-db?authSource=admin # TODO 根据自己的配置修改
#          host: 39.107.102.142
#          port: 27017
#          username: admin
#          password: 123456
            database: test-db
    #配置Mapper.xml映射文件

mybatis:
    mapper-locations:
        - classpath:mapping/*.xml
