server:
   port: 8086
logging:
   config: classpath:log/logback-spring.xml
   file:
      name: ./logback.log
spring:
   application:
      name: elkTest
#log:
#   # logstash 地址和端口，注意修改
#   logstash-host: 192.168.3.233:4560