#端口，项目上下文
server:
   port: 8080
   servlet:
      context-path: /redis-demo

spring:
   redis:
      #    host: 192.168.223.131
      #    port: 7001
      #password: admin@2021
      # Redis 默认数据库设置
      database: 0
      # Redis Cluster集群节点配置
      cluster:
         # Redis 集群地址信息
         nodes:
            - 192.168.10.102:6379
            - 192.168.10.103:6379
            - 192.168.10.104:6379
            - 192.168.10.105:6379
            - 192.168.10.106:6379
            - 192.168.10.107:6379
         # 获取失败 最大重定向次数
         max-redirects: 3
      #如果用以前的jedis，可以把下面的lettuce换成jedis即可
      lettuce:
         pool:
            # 连接池最大连接数默认值为8
            max-active: 1000
            # 连接池最大阻塞时间（使用负值表示没有限制）默认值为-1
            max-wait: -1
            # 连接池中最大空闲连接数默认值为8
            max-idle: 10
            # 连接池中的最小空闲连接数，默认值为0
            min-idle: 10
