server:
   port: 8090
spring:
   application:
      name: jdbc
   profiles:
      active: dynamic
   main:
      allow-bean-definition-overriding: true
      # ====================== ↓↓↓↓↓↓ 配置druid↓↓↓↓↓↓ ======================
   autoconfigure:
      exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
         stat-view-servlet:
            enabled: true
            loginUsername: admin
            loginPassword: 123456
         web-stat-filter:
            enabled: true
mybatis:
   mapper-locations:
      - classpath:mybatis/*.xml
pagehelper:
   helperDialect: mysql
   params: count=countSql
   reasonable: true
   supportMethodsArguments: true