server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.10.251:3306/mybatisdemo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
        username: root
        password: root
        # 配置Druid连接池
        type: com.alibaba.druid.pool.DruidDataSource
        initial-size: 5  # 初始连接池大小
        min-idle: 5      # 最小空闲连接数
        max-active: 20    # 最大活跃连接数
        max-wait: 60000  # 获取连接的最大等待时间（毫秒）
        # Druid监控配置
        druid:
            stat-view-servlet:
                login-username: admin
                login-password: admin
                url-pattern: /druid/*
    application:
        name: MongoDB

    # MongoDB 配置
    data:
        mongodb:
            uri: mongodb://admin:123456@192.168.10.251:27017/test-db?authSource=admin # TODO 根据自己的配置修改
    #      host: 88.90.0.37
    #      port: 27017
    #      username: admin
    #      password: 123456
    #      database: test-db
    #配置Mapper.xml映射文件
mybatis:
    mapper-locations:
        - classpath:mapping/*.xml